[project]
name = "nexus"
version = "0.1.0"
description = "Web app that organizes and presents all components of the ViCoS toolbox"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]",
    "flask-limiter>=4.1.1",
    "mlflow>=3.11.1",
    "python-multipart>=0.0.32",
]

[project.optional-dependencies]
test = [
    "httpx2>=2.12.0",
    "psutil>=7.2.2",
    "pyquery>=2.1.0",
    "pytest>=9.1.1",
    "sseclient>=0.0.27",
]

[tool.pytest.ini_options]
filterwarnings = [
    'ignore::urllib3.exceptions.InsecureRequestWarning'
]
