RUN git clone -b 1.22.0 --depth 1 https://github.com/HumanSignal/label-studio .

COPY ${src}/*.patch .
RUN git apply *.patch && rm *.patch

ADD https://install.python-poetry.org /tmp/install-poetry.py
RUN cd /tmp && uv run python /tmp/install-poetry.py

RUN poetry install
RUN poetry run python label_studio/manage.py collectstatic
RUN --mount=type=cache,target=/root/.yarn make frontend-install frontend-build

RUN poetry install
